// <auto-generated />
using System;
using MedicineDelivery.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicineDelivery.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250919181305_UpdateEntitiesWithNewProperties")]
    partial class UpdateEntitiesWithNewProperties
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.CustomerSupport", b =>
                {
                    b.Property<Guid>("CustomerSupportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AlternativeMobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("CustomerSupportFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerSupportLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerSupportMiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerSupportPhoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CustomerSupportId");

                    b.HasIndex("UserId");

                    b.ToTable("CustomerSupports");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Manager", b =>
                {
                    b.Property<Guid>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AlternativeMobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerMiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ManagerPhoto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ManagerId");

                    b.HasIndex("UserId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.MedicalStore", b =>
                {
                    b.Property<Guid>("MedicalStoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("AlternativeMobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("DLNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FSSAINo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GSTIN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("MedicalName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("OwnerFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerMiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PAN")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PharmacistFirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PharmacistLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PharmacistMobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PharmacistRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("RegistrationStatus")
                        .HasColumnType("bit");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MedicalStoreId");

                    b.HasIndex("UserId");

                    b.ToTable("MedicalStores");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(958),
                            Description = "Can view user information",
                            IsActive = true,
                            Module = "Users",
                            Name = "ReadUsers"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(960),
                            Description = "Can create new users",
                            IsActive = true,
                            Module = "Users",
                            Name = "CreateUsers"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(961),
                            Description = "Can update user information",
                            IsActive = true,
                            Module = "Users",
                            Name = "UpdateUsers"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(963),
                            Description = "Can delete users",
                            IsActive = true,
                            Module = "Users",
                            Name = "DeleteUsers"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(964),
                            Description = "Can view products",
                            IsActive = true,
                            Module = "Products",
                            Name = "ReadProducts"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(965),
                            Description = "Can create new products",
                            IsActive = true,
                            Module = "Products",
                            Name = "CreateProducts"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(966),
                            Description = "Can update products",
                            IsActive = true,
                            Module = "Products",
                            Name = "UpdateProducts"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(967),
                            Description = "Can delete products",
                            IsActive = true,
                            Module = "Products",
                            Name = "DeleteProducts"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(970),
                            Description = "Can view orders",
                            IsActive = true,
                            Module = "Orders",
                            Name = "ReadOrders"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(971),
                            Description = "Can create new orders",
                            IsActive = true,
                            Module = "Orders",
                            Name = "CreateOrders"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(972),
                            Description = "Can update orders",
                            IsActive = true,
                            Module = "Orders",
                            Name = "UpdateOrders"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(973),
                            Description = "Can delete orders",
                            IsActive = true,
                            Module = "Orders",
                            Name = "DeleteOrders"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(975),
                            Description = "Admin can view all user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "AdminReadUsers"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(976),
                            Description = "Admin can create users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "AdminCreateUsers"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(977),
                            Description = "Admin can update user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "AdminUpdateUsers"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(978),
                            Description = "Admin can delete users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "AdminDeleteUsers"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(979),
                            Description = "Manager can view user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ManagerReadUsers"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(981),
                            Description = "Manager can create users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ManagerCreateUsers"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(982),
                            Description = "Manager can update user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ManagerUpdateUsers"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(983),
                            Description = "Manager can delete users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ManagerDeleteUsers"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(984),
                            Description = "CustomerSupport can view user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "CustomerSupportReadUsers"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(986),
                            Description = "CustomerSupport can create users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "CustomerSupportCreateUsers"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(987),
                            Description = "CustomerSupport can update user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "CustomerSupportUpdateUsers"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(988),
                            Description = "CustomerSupport can delete users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "CustomerSupportDeleteUsers"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(989),
                            Description = "Chemist can view user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ChemistReadUsers"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(991),
                            Description = "Chemist can create users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ChemistCreateUsers"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(992),
                            Description = "Chemist can update user information",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ChemistUpdateUsers"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(994),
                            Description = "Chemist can delete users",
                            IsActive = true,
                            Module = "UserManagement",
                            Name = "ChemistDeleteUsers"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(995),
                            Description = "Can manage role permissions",
                            IsActive = true,
                            Module = "RoleManagement",
                            Name = "ManageRolePermission"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(996),
                            Description = "Can read chemist information",
                            IsActive = true,
                            Module = "Chemist",
                            Name = "ChemistRead"
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(998),
                            Description = "Can create chemist accounts",
                            IsActive = true,
                            Module = "Chemist",
                            Name = "ChemistCreate"
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(999),
                            Description = "Can update chemist information",
                            IsActive = true,
                            Module = "Chemist",
                            Name = "ChemistUpdate"
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1000),
                            Description = "Can delete chemist accounts",
                            IsActive = true,
                            Module = "Chemist",
                            Name = "ChemistDelete"
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1001),
                            Description = "Can read customer support information",
                            IsActive = true,
                            Module = "CustomerSupport",
                            Name = "CustomerSupportRead"
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1003),
                            Description = "Can create customer support accounts",
                            IsActive = true,
                            Module = "CustomerSupport",
                            Name = "CustomerSupportCreate"
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1004),
                            Description = "Can update customer support information",
                            IsActive = true,
                            Module = "CustomerSupport",
                            Name = "CustomerSupportUpdate"
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1040),
                            Description = "Can delete customer support accounts",
                            IsActive = true,
                            Module = "CustomerSupport",
                            Name = "CustomerSupportDelete"
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1042),
                            Description = "Can read manager information",
                            IsActive = true,
                            Module = "Manager",
                            Name = "ManagerSupportRead"
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1043),
                            Description = "Can create manager accounts",
                            IsActive = true,
                            Module = "Manager",
                            Name = "ManagerSupportCreate"
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1044),
                            Description = "Can update manager information",
                            IsActive = true,
                            Module = "Manager",
                            Name = "ManagerSupportUpdate"
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1046),
                            Description = "Can delete manager accounts",
                            IsActive = true,
                            Module = "Manager",
                            Name = "ManagerSupportDelete"
                        });
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1252),
                            Description = "Full system access",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1254),
                            Description = "Management level access",
                            IsActive = true,
                            Name = "Manager"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1256),
                            Description = "Customer support access",
                            IsActive = true,
                            Name = "CustomerSupport"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1257),
                            Description = "Customer access",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1262),
                            Description = "Chemist/pharmacist access",
                            IsActive = true,
                            Name = "Chemist"
                        });
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1283),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 2,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1285),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 3,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1286),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 4,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1287),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1289),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1290),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 7,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1291),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 8,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1292),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1293),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1294),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 11,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1295),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 12,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1296),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 13,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1297),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 14,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1298),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 15,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1299),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 16,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1300),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 17,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1301),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 18,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1302),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 19,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1303),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 20,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1304),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1305),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1306),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1307),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 24,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1308),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1309),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1310),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 27,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1311),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 28,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1312),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 29,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1313),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1314),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 31,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1315),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1316),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1317),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1318),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 35,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1319),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1320),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 37,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1321),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 38,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1322),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 39,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1323),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 40,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1324),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 41,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1325),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1326),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 3,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1327),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1328),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 7,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1329),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1330),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 11,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1331),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 17,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1332),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 18,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1333),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 19,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1334),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 20,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1335),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1336),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1337),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1338),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 24,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1339),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1340),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1341),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 27,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1342),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 28,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1343),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1344),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 31,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1345),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1346),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1347),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1348),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 35,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1348),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1349),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 37,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1350),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 38,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1351),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 40,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1352),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 41,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1354),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1355),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1379),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1380),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 21,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1381),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 22,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1382),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 23,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1383),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 24,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1384),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 25,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1385),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 26,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1386),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 27,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1387),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 28,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1388),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1389),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 31,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1390),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1391),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1392),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 34,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1393),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 36,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1394),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 37,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1395),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1396),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1397),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1397),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1398),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 6,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1399),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 7,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1400),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 8,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1401),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 9,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1402),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 10,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1403),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 11,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1404),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 12,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1405),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 30,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1406),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 32,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1407),
                            IsActive = true
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 33,
                            GrantedAt = new DateTime(2025, 9, 19, 18, 13, 3, 250, DateTimeKind.Utc).AddTicks(1408),
                            IsActive = true
                        });
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MedicineDelivery.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.CustomerSupport", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Manager", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.MedicalStore", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicineDelivery.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicineDelivery.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("MedicineDelivery.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicineDelivery.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MedicineDelivery.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MedicineDelivery.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicineDelivery.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MedicineDelivery.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("MedicineDelivery.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
