CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FirstName" text,
        "LastName" text,
        "Gender" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Permissions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Module" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric NOT NULL,
        "Category" text NOT NULL,
        "Description" text NOT NULL,
        "StockQuantity" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Customers" (
        "CustomerId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CustomerFirstName" character varying(100) NOT NULL,
        "CustomerLastName" character varying(100) NOT NULL,
        "CustomerMiddleName" character varying(100),
        "MobileNumber" character varying(15) NOT NULL,
        "AlternativeMobileNumber" character varying(15),
        "EmailId" character varying(50),
        "DateOfBirth" timestamp with time zone NOT NULL,
        "Gender" character varying(10),
        "CustomerPhoto" character varying(255),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedOn" timestamp with time zone,
        "UserId" text,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId"),
        CONSTRAINT "FK_Customers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "CustomerSupports" (
        "CustomerSupportId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CustomerSupportFirstName" character varying(100) NOT NULL,
        "CustomerSupportLastName" character varying(100) NOT NULL,
        "CustomerSupportMiddleName" character varying(100) NOT NULL,
        "Address" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "EmployeeId" character varying(50) NOT NULL,
        "CustomerSupportPhoto" character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_CustomerSupports" PRIMARY KEY ("CustomerSupportId"),
        CONSTRAINT "FK_CustomerSupports_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Managers" (
        "ManagerId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ManagerFirstName" character varying(100) NOT NULL,
        "ManagerLastName" character varying(100) NOT NULL,
        "ManagerMiddleName" character varying(100) NOT NULL,
        "Address" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "EmployeeId" character varying(50) NOT NULL,
        "ManagerPhoto" character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_Managers" PRIMARY KEY ("ManagerId"),
        CONSTRAINT "FK_Managers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "MedicalStores" (
        "MedicalStoreId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "MedicalName" character varying(100) NOT NULL,
        "OwnerFirstName" character varying(100) NOT NULL,
        "OwnerLastName" character varying(100) NOT NULL,
        "OwnerMiddleName" character varying(100) NOT NULL,
        "AddressLine1" character varying(300) NOT NULL,
        "AddressLine2" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "PostalCode" character varying(20) NOT NULL,
        "Latitude" numeric(18,6),
        "Longitude" numeric(18,6),
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "RegistrationStatus" boolean NOT NULL,
        "GSTIN" character varying(100),
        "PAN" character varying(100) NOT NULL,
        "FSSAINo" character varying(100) NOT NULL,
        "DLNo" character varying(100) NOT NULL,
        "PharmacistFirstName" character varying(100) NOT NULL,
        "PharmacistLastName" character varying(100) NOT NULL,
        "PharmacistRegistrationNumber" character varying(100) NOT NULL,
        "PharmacistMobileNumber" character varying(15) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_MedicalStores" PRIMARY KEY ("MedicalStoreId"),
        CONSTRAINT "FK_MedicalStores_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "RolePermissions" (
        "RoleId" text NOT NULL,
        "PermissionId" integer NOT NULL,
        "GrantedAt" timestamp with time zone NOT NULL,
        "GrantedBy" text,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_RolePermissions_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "CustomerAddresses" (
        "Id" uuid NOT NULL,
        "CustomerId" uuid NOT NULL,
        "Address" character varying(300),
        "AddressLine1" character varying(300),
        "AddressLine2" character varying(300),
        "AddressLine3" character varying(300),
        "City" character varying(100),
        "State" character varying(100),
        "PostalCode" character varying(20),
        "IsDefault" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_CustomerAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerAddresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "OrderId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" uuid NOT NULL,
        "CustomerAddressId" uuid NOT NULL,
        "MedicalStoreId" uuid,
        "AssignedByType" character varying(20) NOT NULL,
        "CustomerSupportId" uuid,
        "OrderType" character varying(20) NOT NULL,
        "OrderInputType" character varying(20) NOT NULL,
        "OrderInputFileLocation" character varying(100),
        "OrderInputText" text,
        "OrderStatus" character varying(50) NOT NULL,
        "OTP" character varying(10),
        "TotalAmount" numeric(10,2),
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_Orders_CustomerAddresses_CustomerAddressId" FOREIGN KEY ("CustomerAddressId") REFERENCES "CustomerAddresses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_CustomerSupports_CustomerSupportId" FOREIGN KEY ("CustomerSupportId") REFERENCES "CustomerSupports" ("CustomerSupportId") ON DELETE SET NULL,
        CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_MedicalStores_MedicalStoreId" FOREIGN KEY ("MedicalStoreId") REFERENCES "MedicalStores" ("MedicalStoreId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "OrderAssignmentHistories" (
        "AssignmentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "MedicalStoreId" uuid NOT NULL,
        "AssignedByType" character varying(20) NOT NULL,
        "AssignedByCustomerSupportId" uuid,
        "AssignedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "Status" character varying(20) NOT NULL,
        "RejectNote" character varying(250),
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_OrderAssignmentHistories" PRIMARY KEY ("AssignmentId"),
        CONSTRAINT "FK_OrderAssignmentHistories_CustomerSupports_AssignedByCustome~" FOREIGN KEY ("AssignedByCustomerSupportId") REFERENCES "CustomerSupports" ("CustomerSupportId") ON DELETE SET NULL,
        CONSTRAINT "FK_OrderAssignmentHistories_MedicalStores_MedicalStoreId" FOREIGN KEY ("MedicalStoreId") REFERENCES "MedicalStores" ("MedicalStoreId") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrderAssignmentHistories_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "PaymentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "PaymentMode" character varying(50) NOT NULL,
        "TransactionId" character varying(100) NOT NULL,
        "Amount" numeric(10,2) NOT NULL,
        "PaymentStatus" character varying(50) NOT NULL,
        "PaidOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_CustomerAddresses_CustomerId" ON "CustomerAddresses" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Customers_UserId" ON "Customers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_CustomerSupports_UserId" ON "CustomerSupports" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Managers_UserId" ON "Managers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_MedicalStores_UserId" ON "MedicalStores" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_AssignedByCustomerSupportId" ON "OrderAssignmentHistories" ("AssignedByCustomerSupportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_MedicalStoreId" ON "OrderAssignmentHistories" ("MedicalStoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_OrderId" ON "OrderAssignmentHistories" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_Status" ON "OrderAssignmentHistories" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerAddressId" ON "Orders" ("CustomerAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerSupportId" ON "Orders" ("CustomerSupportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_MedicalStoreId" ON "Orders" ("MedicalStoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_OrderStatus" ON "Orders" ("OrderStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_TransactionId" ON "Payments" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251120075255_InitialCreate', '8.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ALTER COLUMN "OTP" TYPE character varying(4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ADD "OrderNumber" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Latitude" numeric(10,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Longitude" numeric(11,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251202165943_AddOrderNumberAndCustomerAddressCoordinates', '8.0.0');
    END IF;
END $EF$;
COMMIT;

