CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetRoles" (
        "Id" text NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUsers" (
        "Id" text NOT NULL,
        "FirstName" text,
        "LastName" text,
        "Gender" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL,
        "LastLoginAt" timestamp with time zone,
        "IsActive" boolean NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Permissions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Description" text NOT NULL,
        "Module" text NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Products" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Price" numeric NOT NULL,
        "Category" text NOT NULL,
        "Description" text NOT NULL,
        "StockQuantity" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_Products" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" text NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserRoles" (
        "UserId" text NOT NULL,
        "RoleId" text NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "AspNetUserTokens" (
        "UserId" text NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Customers" (
        "CustomerId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CustomerFirstName" character varying(100) NOT NULL,
        "CustomerLastName" character varying(100) NOT NULL,
        "CustomerMiddleName" character varying(100),
        "MobileNumber" character varying(15) NOT NULL,
        "AlternativeMobileNumber" character varying(15),
        "EmailId" character varying(50),
        "DateOfBirth" timestamp with time zone NOT NULL,
        "Gender" character varying(10),
        "CustomerPhoto" character varying(255),
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedOn" timestamp with time zone,
        "UserId" text,
        CONSTRAINT "PK_Customers" PRIMARY KEY ("CustomerId"),
        CONSTRAINT "FK_Customers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "CustomerSupports" (
        "CustomerSupportId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "CustomerSupportFirstName" character varying(100) NOT NULL,
        "CustomerSupportLastName" character varying(100) NOT NULL,
        "CustomerSupportMiddleName" character varying(100) NOT NULL,
        "Address" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "EmployeeId" character varying(50) NOT NULL,
        "CustomerSupportPhoto" character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_CustomerSupports" PRIMARY KEY ("CustomerSupportId"),
        CONSTRAINT "FK_CustomerSupports_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Managers" (
        "ManagerId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "ManagerFirstName" character varying(100) NOT NULL,
        "ManagerLastName" character varying(100) NOT NULL,
        "ManagerMiddleName" character varying(100) NOT NULL,
        "Address" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "EmployeeId" character varying(50) NOT NULL,
        "ManagerPhoto" character varying(255) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_Managers" PRIMARY KEY ("ManagerId"),
        CONSTRAINT "FK_Managers_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "MedicalStores" (
        "MedicalStoreId" uuid NOT NULL DEFAULT (gen_random_uuid()),
        "MedicalName" character varying(100) NOT NULL,
        "OwnerFirstName" character varying(100) NOT NULL,
        "OwnerLastName" character varying(100) NOT NULL,
        "OwnerMiddleName" character varying(100) NOT NULL,
        "AddressLine1" character varying(300) NOT NULL,
        "AddressLine2" character varying(300) NOT NULL,
        "City" character varying(100) NOT NULL,
        "State" character varying(100) NOT NULL,
        "PostalCode" character varying(20) NOT NULL,
        "Latitude" numeric(18,6),
        "Longitude" numeric(18,6),
        "MobileNumber" character varying(15) NOT NULL,
        "EmailId" character varying(50) NOT NULL,
        "AlternativeMobileNumber" character varying(15) NOT NULL,
        "RegistrationStatus" boolean NOT NULL,
        "GSTIN" character varying(100),
        "PAN" character varying(100) NOT NULL,
        "FSSAINo" character varying(100) NOT NULL,
        "DLNo" character varying(100) NOT NULL,
        "PharmacistFirstName" character varying(100) NOT NULL,
        "PharmacistLastName" character varying(100) NOT NULL,
        "PharmacistRegistrationNumber" character varying(100) NOT NULL,
        "PharmacistMobileNumber" character varying(15) NOT NULL,
        "IsActive" boolean NOT NULL,
        "IsDeleted" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "CreatedBy" uuid,
        "UpdatedOn" timestamp with time zone,
        "UpdatedBy" uuid,
        "UserId" text,
        CONSTRAINT "PK_MedicalStores" PRIMARY KEY ("MedicalStoreId"),
        CONSTRAINT "FK_MedicalStores_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "RolePermissions" (
        "RoleId" text NOT NULL,
        "PermissionId" integer NOT NULL,
        "GrantedAt" timestamp with time zone NOT NULL,
        "GrantedBy" text,
        "IsActive" boolean NOT NULL,
        CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("RoleId", "PermissionId"),
        CONSTRAINT "FK_RolePermissions_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "CustomerAddresses" (
        "Id" uuid NOT NULL,
        "CustomerId" uuid NOT NULL,
        "Address" character varying(300),
        "AddressLine1" character varying(300),
        "AddressLine2" character varying(300),
        "AddressLine3" character varying(300),
        "City" character varying(100),
        "State" character varying(100),
        "PostalCode" character varying(20),
        "IsDefault" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL,
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_CustomerAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerAddresses_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Orders" (
        "OrderId" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerId" uuid NOT NULL,
        "CustomerAddressId" uuid NOT NULL,
        "MedicalStoreId" uuid,
        "AssignedByType" character varying(20) NOT NULL,
        "CustomerSupportId" uuid,
        "OrderType" character varying(20) NOT NULL,
        "OrderInputType" character varying(20) NOT NULL,
        "OrderInputFileLocation" character varying(100),
        "OrderInputText" text,
        "OrderStatus" character varying(50) NOT NULL,
        "OTP" character varying(10),
        "TotalAmount" numeric(10,2),
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_Orders" PRIMARY KEY ("OrderId"),
        CONSTRAINT "FK_Orders_CustomerAddresses_CustomerAddressId" FOREIGN KEY ("CustomerAddressId") REFERENCES "CustomerAddresses" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_CustomerSupports_CustomerSupportId" FOREIGN KEY ("CustomerSupportId") REFERENCES "CustomerSupports" ("CustomerSupportId") ON DELETE SET NULL,
        CONSTRAINT "FK_Orders_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT,
        CONSTRAINT "FK_Orders_MedicalStores_MedicalStoreId" FOREIGN KEY ("MedicalStoreId") REFERENCES "MedicalStores" ("MedicalStoreId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "OrderAssignmentHistories" (
        "AssignmentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "MedicalStoreId" uuid NOT NULL,
        "AssignedByType" character varying(20) NOT NULL,
        "AssignedByCustomerSupportId" uuid,
        "AssignedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "Status" character varying(20) NOT NULL,
        "RejectNote" character varying(250),
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_OrderAssignmentHistories" PRIMARY KEY ("AssignmentId"),
        CONSTRAINT "FK_OrderAssignmentHistories_CustomerSupports_AssignedByCustome~" FOREIGN KEY ("AssignedByCustomerSupportId") REFERENCES "CustomerSupports" ("CustomerSupportId") ON DELETE SET NULL,
        CONSTRAINT "FK_OrderAssignmentHistories_MedicalStores_MedicalStoreId" FOREIGN KEY ("MedicalStoreId") REFERENCES "MedicalStores" ("MedicalStoreId") ON DELETE RESTRICT,
        CONSTRAINT "FK_OrderAssignmentHistories_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "PaymentId" integer GENERATED BY DEFAULT AS IDENTITY,
        "OrderId" integer NOT NULL,
        "PaymentMode" character varying(50) NOT NULL,
        "TransactionId" character varying(100) NOT NULL,
        "Amount" numeric(10,2) NOT NULL,
        "PaymentStatus" character varying(50) NOT NULL,
        "PaidOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        CONSTRAINT "PK_Payments" PRIMARY KEY ("PaymentId"),
        CONSTRAINT "FK_Payments_Orders_OrderId" FOREIGN KEY ("OrderId") REFERENCES "Orders" ("OrderId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_CustomerAddresses_CustomerId" ON "CustomerAddresses" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Customers_UserId" ON "Customers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_CustomerSupports_UserId" ON "CustomerSupports" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Managers_UserId" ON "Managers" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_MedicalStores_UserId" ON "MedicalStores" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_AssignedByCustomerSupportId" ON "OrderAssignmentHistories" ("AssignedByCustomerSupportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_MedicalStoreId" ON "OrderAssignmentHistories" ("MedicalStoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_OrderId" ON "OrderAssignmentHistories" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_Status" ON "OrderAssignmentHistories" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerAddressId" ON "Orders" ("CustomerAddressId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerId" ON "Orders" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_CustomerSupportId" ON "Orders" ("CustomerSupportId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_MedicalStoreId" ON "Orders" ("MedicalStoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Orders_OrderStatus" ON "Orders" ("OrderStatus");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_Payments_OrderId" ON "Payments" ("OrderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Payments_TransactionId" ON "Payments" ("TransactionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251120075255_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251120075255_InitialCreate', '8.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ALTER COLUMN "OTP" TYPE character varying(4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ADD "OrderNumber" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Latitude" numeric(10,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Longitude" numeric(11,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251202165943_AddOrderNumberAndCustomerAddressCoordinates', '8.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ALTER COLUMN "OTP" TYPE character varying(4);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "Orders" ADD "OrderNumber" character varying(10);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Latitude" numeric(10,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    ALTER TABLE "CustomerAddresses" ADD "Longitude" numeric(11,8);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251202165943_AddOrderNumberAndCustomerAddressCoordinates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251202165943_AddOrderNumberAndCustomerAddressCoordinates', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "Orders" ADD "AssignTo" character varying(20) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "Orders" ADD "DeliveryId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "Orders" ADD "OrderBillFileLocation" character varying(255);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ALTER COLUMN "MedicalStoreId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ADD "AssignTo" character varying(20) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ADD "CustomerId" uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ADD "DeliveryId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "CustomerSupports" ADD "CustomerSupportRegionId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE TABLE "CustomerSupportRegions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100) NOT NULL,
        "City" character varying(100) NOT NULL,
        "RegionName" character varying(100) NOT NULL,
        CONSTRAINT "PK_CustomerSupportRegions" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE TABLE "Deliveries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(100),
        "MiddleName" character varying(100),
        "LastName" character varying(100),
        "DrivingLicenceNumber" character varying(50),
        "MobileNumber" character varying(15),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "IsDeleted" boolean NOT NULL DEFAULT FALSE,
        "MedicalStoreId" uuid,
        "AddedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "ModifiedOn" timestamp with time zone,
        "AddedBy" uuid,
        "ModifiedBy" uuid,
        CONSTRAINT "PK_Deliveries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Deliveries_MedicalStores_MedicalStoreId" FOREIGN KEY ("MedicalStoreId") REFERENCES "MedicalStores" ("MedicalStoreId") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE TABLE "CustomerSupportRegionPinCodes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CustomerSupportRegionId" integer NOT NULL,
        "PinCode" character varying(10) NOT NULL,
        CONSTRAINT "PK_CustomerSupportRegionPinCodes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CustomerSupportRegionPinCodes_CustomerSupportRegions_Custom~" FOREIGN KEY ("CustomerSupportRegionId") REFERENCES "CustomerSupportRegions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_Orders_DeliveryId" ON "Orders" ("DeliveryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_CustomerId" ON "OrderAssignmentHistories" ("CustomerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_OrderAssignmentHistories_DeliveryId" ON "OrderAssignmentHistories" ("DeliveryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupports_CustomerSupportRegionId" ON "CustomerSupports" ("CustomerSupportRegionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupportRegionPinCodes_CustomerSupportRegionId" ON "CustomerSupportRegionPinCodes" ("CustomerSupportRegionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE UNIQUE INDEX "IX_CustomerSupportRegionPinCodes_CustomerSupportRegionId_PinCo~" ON "CustomerSupportRegionPinCodes" ("CustomerSupportRegionId", "PinCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupportRegionPinCodes_PinCode" ON "CustomerSupportRegionPinCodes" ("PinCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupportRegions_City" ON "CustomerSupportRegions" ("City");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupportRegions_Name" ON "CustomerSupportRegions" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_CustomerSupportRegions_RegionName" ON "CustomerSupportRegions" ("RegionName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_Deliveries_IsActive" ON "Deliveries" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_Deliveries_IsDeleted" ON "Deliveries" ("IsDeleted");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    CREATE INDEX "IX_Deliveries_MedicalStoreId" ON "Deliveries" ("MedicalStoreId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "CustomerSupports" ADD CONSTRAINT "FK_CustomerSupports_CustomerSupportRegions_CustomerSupportRegi~" FOREIGN KEY ("CustomerSupportRegionId") REFERENCES "CustomerSupportRegions" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ADD CONSTRAINT "FK_OrderAssignmentHistories_Customers_CustomerId" FOREIGN KEY ("CustomerId") REFERENCES "Customers" ("CustomerId") ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "OrderAssignmentHistories" ADD CONSTRAINT "FK_OrderAssignmentHistories_Deliveries_DeliveryId" FOREIGN KEY ("DeliveryId") REFERENCES "Deliveries" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    ALTER TABLE "Orders" ADD CONSTRAINT "FK_Orders_Deliveries_DeliveryId" FOREIGN KEY ("DeliveryId") REFERENCES "Deliveries" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251218062927_AddedGroupsAndItsRelatedColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251218062927_AddedGroupsAndItsRelatedColumns', '8.0.0');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE TABLE "Consents" (
        "ConsentId" uuid NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" character varying(1000),
        "Content" text NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        "UpdatedOn" timestamp with time zone,
        CONSTRAINT "PK_Consents" PRIMARY KEY ("ConsentId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE TABLE "ConsentLogs" (
        "ConsentLogId" uuid NOT NULL,
        "ConsentId" uuid NOT NULL,
        "UserId" text NOT NULL,
        "UserType" integer NOT NULL,
        "RespectiveId" uuid,
        "Action" integer NOT NULL,
        "UserAgent" character varying(500) NOT NULL,
        "IpAddress" character varying(50) NOT NULL,
        "DeviceInfo" character varying(500),
        "CreatedOn" timestamp with time zone NOT NULL DEFAULT (now() at time zone 'utc'),
        CONSTRAINT "PK_ConsentLogs" PRIMARY KEY ("ConsentLogId"),
        CONSTRAINT "FK_ConsentLogs_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE RESTRICT,
        CONSTRAINT "FK_ConsentLogs_Consents_ConsentId" FOREIGN KEY ("ConsentId") REFERENCES "Consents" ("ConsentId") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_ConsentLogs_ConsentId" ON "ConsentLogs" ("ConsentId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_ConsentLogs_CreatedOn" ON "ConsentLogs" ("CreatedOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_ConsentLogs_UserId" ON "ConsentLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_ConsentLogs_UserType" ON "ConsentLogs" ("UserType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_Consents_CreatedOn" ON "Consents" ("CreatedOn");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    CREATE INDEX "IX_Consents_IsActive" ON "Consents" ("IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260116175330_AddConsentAndConsentLogTables') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260116175330_AddConsentAndConsentLogTables', '8.0.0');
    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

-- Migration: 20260201191445_AddOrderPaymentStatus

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260201191445_AddOrderPaymentStatus') THEN
    ALTER TABLE "Orders" ADD "OrderPaymentStatus" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260201191445_AddOrderPaymentStatus') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260201191445_AddOrderPaymentStatus', '8.0.0');
    END IF;
END $EF$;

COMMIT;

START TRANSACTION;

-- Migration: 20260208175510_RenameToServiceRegionAndAddRegionType

-- Drop existing foreign keys that reference the old column names
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupportRegionPinCodes" DROP CONSTRAINT IF EXISTS "FK_CustomerSupportRegionPinCodes_CustomerSupportRegions_Custom~";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupports" DROP CONSTRAINT IF EXISTS "FK_CustomerSupports_CustomerSupportRegions_CustomerSupportRegi~";
    END IF;
END $EF$;

-- Rename column CustomerSupportRegionId -> ServiceRegionId in CustomerSupports
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupports" RENAME COLUMN "CustomerSupportRegionId" TO "ServiceRegionId";
    END IF;
END $EF$;

-- Rename index on CustomerSupports
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER INDEX IF EXISTS "IX_CustomerSupports_CustomerSupportRegionId" RENAME TO "IX_CustomerSupports_ServiceRegionId";
    END IF;
END $EF$;

-- Rename column CustomerSupportRegionId -> ServiceRegionId in CustomerSupportRegionPinCodes
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupportRegionPinCodes" RENAME COLUMN "CustomerSupportRegionId" TO "ServiceRegionId";
    END IF;
END $EF$;

-- Rename unique index on CustomerSupportRegionPinCodes (composite)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER INDEX IF EXISTS "IX_CustomerSupportRegionPinCodes_CustomerSupportRegionId_PinCo~" RENAME TO "IX_CustomerSupportRegionPinCodes_ServiceRegionId_PinCode";
    END IF;
END $EF$;

-- Rename single-column index on CustomerSupportRegionPinCodes
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER INDEX IF EXISTS "IX_CustomerSupportRegionPinCodes_CustomerSupportRegionId" RENAME TO "IX_CustomerSupportRegionPinCodes_ServiceRegionId";
    END IF;
END $EF$;

-- Add ServiceRegionId column to Deliveries
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "Deliveries" ADD "ServiceRegionId" integer;
    END IF;
END $EF$;

-- Add RegionType column to CustomerSupportRegions (default 0 = CustomerSupport)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupportRegions" ADD "RegionType" integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

-- Create index on Deliveries.ServiceRegionId
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    CREATE INDEX "IX_Deliveries_ServiceRegionId" ON "Deliveries" ("ServiceRegionId");
    END IF;
END $EF$;

-- Create index on CustomerSupportRegions.RegionType
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    CREATE INDEX "IX_CustomerSupportRegions_RegionType" ON "CustomerSupportRegions" ("RegionType");
    END IF;
END $EF$;

-- Re-create foreign key: CustomerSupportRegionPinCodes -> CustomerSupportRegions (using new column name)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupportRegionPinCodes" ADD CONSTRAINT "FK_CustomerSupportRegionPinCodes_CustomerSupportRegions_Servic~" FOREIGN KEY ("ServiceRegionId") REFERENCES "CustomerSupportRegions" ("Id") ON DELETE CASCADE;
    END IF;
END $EF$;

-- Re-create foreign key: CustomerSupports -> CustomerSupportRegions (using new column name)
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "CustomerSupports" ADD CONSTRAINT "FK_CustomerSupports_CustomerSupportRegions_ServiceRegionId" FOREIGN KEY ("ServiceRegionId") REFERENCES "CustomerSupportRegions" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

-- Add foreign key: Deliveries -> CustomerSupportRegions
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    ALTER TABLE "Deliveries" ADD CONSTRAINT "FK_Deliveries_CustomerSupportRegions_ServiceRegionId" FOREIGN KEY ("ServiceRegionId") REFERENCES "CustomerSupportRegions" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

-- Record migration as applied
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260208175510_RenameToServiceRegionAndAddRegionType') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260208175510_RenameToServiceRegionAndAddRegionType', '8.0.0');
    END IF;
END $EF$;

COMMIT;

-- ============================================================================
-- Migration: 20260210182454_AddDeliveryUserIdAndCustomerNumber
-- Adds UserId column to Deliveries (FK to AspNetUsers) and
-- CustomerNumber column to Customers (8-char unique alphanumeric)
-- ============================================================================
START TRANSACTION;

-- Add UserId column to Deliveries
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    ALTER TABLE "Deliveries" ADD "UserId" text NULL;
    END IF;
END $EF$;

-- Add CustomerNumber column to Customers
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    ALTER TABLE "Customers" ADD "CustomerNumber" character varying(8) NOT NULL DEFAULT '';
    END IF;
END $EF$;

-- Create index on Deliveries.UserId
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    CREATE INDEX "IX_Deliveries_UserId" ON "Deliveries" ("UserId");
    END IF;
END $EF$;

-- Create unique index on Customers.CustomerNumber
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    CREATE UNIQUE INDEX "IX_Customers_CustomerNumber" ON "Customers" ("CustomerNumber");
    END IF;
END $EF$;

-- Add foreign key: Deliveries.UserId -> AspNetUsers.Id
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    ALTER TABLE "Deliveries" ADD CONSTRAINT "FK_Deliveries_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

-- Record migration as applied
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260210182454_AddDeliveryUserIdAndCustomerNumber') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260210182454_AddDeliveryUserIdAndCustomerNumber', '8.0.0');
    END IF;
END $EF$;

COMMIT;

